name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Check formatting
      run: |
        npx prettier --check .

    - name: Run ESLint
      run: npm run lint

    - name: Build project
      run: npm run build
      
    - name: Send WhatsApp notification on failure
      if: failure()
      uses: muinmundzir/whatsapp-action@v1
      with:
        number: "8085121735"
        message: "❌ Build failed for ${{ github.repository }}! Check the logs at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"